workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      ios_signing:
        distribution_type: ad_hoc
        bundle_id: com.fossasia.openevent
    scripts:
      - name: Install dependencies
        script: |
          pod install
      - name: Build
        script: |
          xcodebuild build -workspace FOSSAsia.xcworkspace -scheme "FOSSAsia" -configuration Release -derivedDataPath build
    artifacts:
      - build/Build/Products/Release-iphoneos/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
