workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      ios_signing:
        distribution_type: ad_hoc
    scripts:
      - name: Install dependencies
        script: |
          cd ios
          pod install
      - name: Build
        script: |
          cd ios
          xcodebuild build -workspace open-event-ios.xcworkspace -scheme "open-event-ios" -configuration Release -derivedDataPath build
    artifacts:
      - build/Build/Products/Release-iphoneos/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
